### ISSUE TITLE
Folder issue

### ISSUE THREAD

**Issue by revilo951** [KodeStar/audiosilo#5]
Having an issue with selecting another folder. The first directory specified in the command works fine, but selecting another from the dropdown, I get this output in the browser console:

(It also seems to break the play/pause rewind/skip buttons too. They work OK prior to changing folders, but not after.)

```f68ea98.js:1 GET https://audioserve.snip/folder//library 404
(anonymous) @ f68ea98.js:1
v @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
r @ 7822ae3.js:2
l @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
F @ f68ea98.js:1
(anonymous) @ 7822ae3.js:2
m.dispatch @ 7822ae3.js:2
dispatch @ 7822ae3.js:2
handler @ 8c272ec.js:1
ee @ 7822ae3.js:2
Tn.run @ 7822ae3.js:2
Sn @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
ce @ 7822ae3.js:2
Promise.then (async)
oe @ 7822ae3.js:2
pe @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
Tn.update @ 7822ae3.js:2
xt.notify @ 7822ae3.js:2
set @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
qt.updateRoute @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
r @ 7822ae3.js:2
jt @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
r @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
x @ 7822ae3.js:2
r @ 7822ae3.js:2
r @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 556a0fa.js:2
x @ 7822ae3.js:2
r @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 556a0fa.js:2
v @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
r @ 7822ae3.js:2
l @ 7822ae3.js:2
Promise.then (async)
r @ 7822ae3.js:2
l @ 7822ae3.js:2
Promise.then (async)
r @ 7822ae3.js:2
l @ 7822ae3.js:2
Promise.then (async)
r @ 7822ae3.js:2
l @ 7822ae3.js:2
Promise.then (async)
r @ 7822ae3.js:2
l @ 7822ae3.js:2
Promise.then (async)
r @ 7822ae3.js:2
l @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
B @ 556a0fa.js:2
x @ 7822ae3.js:2
r @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 556a0fa.js:2
v @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
r @ 7822ae3.js:2
l @ 7822ae3.js:2
Promise.then (async)
r @ 7822ae3.js:2
l @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
C @ 556a0fa.js:2
x @ 7822ae3.js:2
r @ 7822ae3.js:2
jt @ 7822ae3.js:2
qt.confirmTransition @ 7822ae3.js:2
qt.transitionTo @ 7822ae3.js:2
e.push @ 7822ae3.js:2
ee.push @ 7822ae3.js:2
C.n.push @ 556a0fa.js:2
D @ f68ea98.js:1
(anonymous) @ 7822ae3.js:2
m.dispatch @ 7822ae3.js:2
dispatch @ 7822ae3.js:2
(anonymous) @ 8c272ec.js:1
v @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
r @ 7822ae3.js:2
l @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
currentCollection @ 8c272ec.js:1
ee @ 7822ae3.js:2
Tn.run @ 7822ae3.js:2
Sn @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
ce @ 7822ae3.js:2
Promise.then (async)
oe @ 7822ae3.js:2
pe @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
Tn.update @ 7822ae3.js:2
xt.notify @ 7822ae3.js:2
set @ 7822ae3.js:2
$ @ f68ea98.js:1
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
(anonymous) @ 7822ae3.js:2
m._withCommit @ 7822ae3.js:2
m.commit @ 7822ae3.js:2
commit @ 7822ae3.js:2
changeCollection @ f68ea98.js:1
ee @ 7822ae3.js:2
n @ 7822ae3.js:2
Nr.c._wrapper @ 7822ae3.js:2
ListPicker._handleMouseUp @ unknown
Show 22 more frames
VM196:1 Uncaught (in promise) SyntaxError: Unexpected token N in JSON at position 0```

**Comment by revilo951** [comment]
OK that doesn't seem like it'll be of any help - not sure it copied what I thought it had

```f68ea98.js:1 GET https://audioserve.snip/folder//library 404```

**Comment by KodeStar** [comment]
What steps can I do to recreate this? That error message is saying the folder you went to doesn't exist. Is there a `/` in the name? That might break it. What's the output of `https://audioserve.snip/folder/`?

**Comment by KodeStar** [comment]
What do you mean by the command? I have lots of directories and no issues, so it's hard to work out what issue you are having and why. Maybe some screenshots might help?

**Comment by revilo951** [comment]
Yep, that'll be confusing. Not the audiosilo command, I meant to say the audioserve command. I have the volumes added to my audioserve container, and specified in the "command" for the container.

Audioserve logs give me this when I try to change folder:
```audioserve                | [2021-09-28T11:54:04Z ERROR audioserve::services::auth] Invalid access: missing token on path /folder, client: Some(Direct(172.21.0.33))```

It's making a liar out of me with the play/pause button thing though. Screenshot attached, if that helps.
![chrome_rsioOE7bFO](https://user-images.githubusercontent.com/13210587/135085458-4e41bdd2-832d-4775-9b15-c658b3ecaacb.png)

This is directly after clicking the "podgrab" folder (the folder changer dropdown being active is for demonstration only - I clicked the dropdown again before I grabbed the screenshot)

**Comment by KodeStar** [comment]
ohhhh, we are talking collections. Now it makes more sense. I haven't actually tested it much with collections so it's not entirely surprising that it's not working properly. That said I have done *some* testing, so it shouldn't be completely broken. From what I can tell it looks like it's not picking up the collection ID. I'll have a look see if I can replicate and fix

**Comment by KodeStar** [comment]
Should be fixed

**Comment by revilo951** [comment]
Re-built with the current version, now I'm getting 404's in the console - seems to be trying to hit /folder/ which doesn't exist
![chrome_EEy30FOrie](https://user-images.githubusercontent.com/13210587/135229891-e6c379e5-6651-462e-961a-14a178e96f87.png)
.

**Comment by KodeStar** [comment]
`/folder/` is the api request that pulls back the contents of the folder, I've made some changes which might help. You also need to hit the logout button and click login again as that's when it refreshes collections

**Comment by revilo951** [comment]
I wondered if it might be something cached that was causing the problem, so I tried from an incognito window (screenshot is from incognito).

I'll re-build and update you.

**Comment by revilo951** [comment]
OK, that's working nicely! There seems to be something happening with audiosilo caching the shared secret, but I'm gonna dig a bit more and get back to you.

Also, for your to-do list: There doesn't seem to be any way to change collections in the mobile UI.
